---
- name: Call groovy script, get result, handle exceptions
  block:
    - name: Calling Groovy script {{ script_name }}
      vars:
        api_url: "{{ nexus_api_scheme }}://{{ nexus_api_hostname }}:{{ nexus_api_port }}"
        ressource_path: "{{ nexus_api_context_path }}{{ nexus_rest_api_endpoint }}/{{ script_name }}/run"
      ansible.builtin.uri:
        url: "{{ api_url }}{{ ressource_path }}"
        timeout: "{{ nexus_api_timeout | int }}"
        user: admin
        password: "{{ current_nexus_admin_password }}"
        headers:
          Content-Type: text/plain
        method: POST
        force_basic_auth: true
        validate_certs: "{{ nexus_api_validate_certs }}"
        body: "{{ args | to_json }}"
      register: script_run
      failed_when: script_run | nexus_groovy_error | bool
      changed_when: script_run | nexus_groovy_changed | bool

    - name: Details about run script if verbose mode is on
      ansible.builtin.debug:
        msg: "{{ script_run | nexus_groovy_details }}"
        verbosity: 1
      when: not ansible_check_mode

  rescue:
    - name: Handle script failure with debugging
      when: script_run | nexus_groovy_details == 'Global script failure'
      block:
        - name: Debug script result for global fail
          ansible.builtin.debug:
            var: script_run

        - name: Global script failure at nexus level
          ansible.builtin.fail:
            msg: >-
              Running the script {{ script_name }} failed at nexus level.
              See the above debug output

    - name: Debug script result for failed script actions
      ansible.builtin.debug:
        msg: "{{ script_run | nexus_groovy_details }}"

    - name: Script action failure
      ansible.builtin.fail:
        msg: >-
          The script {{ script_name }} returned at least one of its
          actions has failed. See the debug message above for details
