---
- name: Make sure nexus is stopped
  debug:
    msg: "trigger nexus stop"
  changed_when: true
  notify:
    - nexus-service-stop

- meta: flush_handlers

- name: "Purge Nexus"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ nexus_data_dir }}"
    - "{{ nexus_installation_dir }}/nexus-{{ nexus_version }}"
    - "{{ nexus_restore_log }}"
    # - "{{ nexus_backup_dir }}" # Optional

- name: "remove nexus package if present"
  package:
    name: nexus
    state: absent
